---
meta:
  version: "1.0"
  profile: "default"

execution:
  always_elevated: false
  check_mode: false

package_managers:
  detect_automatically: true

global_paths:
  home_dir: "{{ ansible_user_dir | default('~') }}"

selections:
  apps:
    chrome:
      enabled: false
      add_to_dock: true
    vscode:
      enabled: true
      add_to_dock: true
      version: "latest"
      custom_paths:
        install_dir: ""
        config_dir: ""
      settings:
        telemetry.enableTelemetry: false
        telemetry.enableCrashReporter: false
        editor.fontSize: 13
      extensions:
        - ms-python.python
        - redhat.ansible
      os_overrides:
        mac:
          custom_paths:
            config_dir: "~/Library/Application Support/Code/User"
        linux:
          package_manager: "auto"
          custom_paths:
            config_dir: "~/.config/Code/User"
        win:
          custom_paths:
            config_dir: "%APPDATA%\\Code\\User"
    sourcetree:
      enabled: false
    jetbrains_toolbox:
      enabled: false
    android_studio:
      enabled: false
      add_to_dock: false
    sublime:
      enabled: false
    steam:
      enabled: false
    discord:
      enabled: false
    spotify:
      enabled: false
    notion:
      enabled: false
    postman:
      enabled: false
    slack:
      enabled: false
    obs_studio:
      enabled: false
    docker_desktop:
      enabled: false
    freedownloadmanager:
      enabled: false
    localsend:
      enabled: false
    wechat:
      enabled: false
    pixpin:
      enabled: false
      add_to_dock: false
    google_drive:
      enabled: false
    iterm:
      enabled: false
    charles:
      enabled: false
    betterdisplay:
      enabled: false
    stats:
      enabled: false
    appcleaner:
      enabled: false
    macs_fan_control:
      enabled: false
    displaylink_manager:
      enabled: false
    handbrake:
      enabled: false
    iina:
      enabled: false
    raycast:
      enabled: false
      add_to_dock: false
    xcode:
      enabled: false
      add_to_dock: false
    utm:
      enabled: false
      add_to_dock: false
    gnome_tweaks:
      enabled: false
    gnome_shell_extensions:
      enabled: false
    wsl2:
      enabled: false
    windows_terminal:
      enabled: false
    winget:
      enabled: false
    powershell:
      enabled: false

  commandline_tools:
    nodejs:
      enabled: false
    zsh_ohmyzsh:
      enabled: false
      custom_paths:
        install_dir: "~/.config/ohmyzsh"
    opencode:
      enabled: false
    gemini:
      enabled: false
    claudcode:
      enabled: false
    openjdk-latest:
      enabled: false
    openjdk-17:
      enabled: false
    mole:
      enabled: false
    mist_cli:
      enabled: false

  settings:
    setup_ssh_git:
      enabled: false
      user_name: ""
      user_email: ""
      github_accounts: []
    setup_environment:
      enabled: false
      env_sh: |
        # managed by ossetuphelper
        export PATH="$HOME/.local/bin:$PATH"
      app_files: {}
    macos_tweaks:
      enabled: false
      hostname: ""
      setup_dock: false
      clean_docker_icon: true
      allow_mouse_right_click: true
      swap_external_keyboard_cmd_opt: false
      allow_tap_to_click: true
      show_hidden_files: false
      show_all_filename_extensions: true
      allow_three_finger_drag: false

